import type { Metadata } from 'next'
import { Inter, Quicksand } from 'next/font/google'
import './globals.css'
import { CartProvider } from '@/providers/cartProvider'
import { RouteProvider } from '@/providers/routeProvider'

// const inter = Inter({ subsets: ['latin'] })

const quicksand = Quicksand({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <RouteProvider>
          <CartProvider>
            {children}
          </CartProvider>
        </RouteProvider>
      </body>
    </html>
  )
}
